# Generated by Django 4.2.13 on 2024-06-02 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment_name', models.CharField(max_length=180)),
                ('environment_description', models.TextField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solution_name', models.CharField(max_length=180)),
                ('solution_description', models.CharField(max_length=180)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('computer_name', models.CharField(max_length=180)),
                ('computer_ip', models.CharField(max_length=180)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solutions.environment')),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solutions.solution')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
